version: "3"
services:
  bankapi-connect:
    build:
      context: .
      
    env_file:
      - .env
    ports:
      - "8080:8080"

    command: uvicorn app.rest.main:app --reload --host 0.0.0.0 --port 8080