version: "3"
services:
  bankapi-connect:
    build:
      context: .
    ports:
      - "8080:8080"
  
    env_file:
      - .env
    volumes:
      - ./:/app/

    command: uvicorn app.rest.main:app --host 0.0.0.0 --port 8000